- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_packages_taps:
      - homebrew/binary
      - homebrew/dupes
    homebrew_packages_packages:
      - { name: emacs }
      - { name: vim }
      - { name: git }
      - { name: hub }
      - { name: mercurial }
      - { name: tmux }
      - { name: whois }
      - { name: node }
      - { name: wget }
      - { name: nkf }
      - { name: nmap }
      - { name: zsh, install_options: disable-etcdir }
    homebrew_cask_packages_packages:
      -  karabiner
      -  iterm2
      -  atom
      -  firefox
      -  google-chrome
      -  coteditor
      -  dash
      -  dropbox
      -  evernote
      -  vlc
  roles:
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages
