- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_packages_taps:
      - homebrew/binary
      - homebrew/dupes
    homebrew_packages_packages:
      - { name: emacs }
      - { name: vim }
      - { name: git }
      - { name: hub }
      - { name: gs }
      - { name: peco }
      - { name: mercurial }
      - { name: tmux }
      - { name: whois }
      - { name: node }
      - { name: wget }
      - { name: nkf }
      - { name: nmap }
      - { name: tree }
      - { name: go }
      - { name: peco }
      - { name: gibo }
      - { name: zsh, install_options: disable-etcdir }
      - { name: caskroom/cask/brew-cask }
    homebrew_cask_packages_packages:
      -  karabiner
      -  iterm2
      -  atom
      -  firefox
      -  google-chrome
      -  dropbox
      -  vlc
      -  bettertouchtool
      -  google-drive
      -  teleport
      -  virtualbox
      -  vagrant
      -  firealpaca
      -  skype
      -  nylas-n1
  roles:
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages
#    - copyroll
